
export const REPO_FETCHER_PORT = Symbol('REPO_FETCHER_PORT');
export const STATIC_ANALYZER_PORT = Symbol('STATIC_ANALYZER_PORT');
export const AI_ANALYZER_PORT = Symbol('AI_ANALYZER_PORT');
export const ANALYSIS_REPOSITORY_PORT = Symbol('ANALYSIS_REPOSITORY_PORT');
export const ANALYSIS_QUEUE_PORT = Symbol('ANALYSIS_QUEUE_PORT');
export const ZIP_UPLOAD_PORT = Symbol('ZIP_UPLOAD_PORT');
export const RATE_LIMITER_PORT = Symbol('RATE_LIMITER_PORT');
